### ISSUE TITLE
[CI] Integrate Codecov for Automated Code Coverage Analysis

### ISSUE THREAD

**Issue by pedrobiqua** [pedrobiqua/Search_Engine#36]
# Feature Request

## Description

Integrate Codecov into the repository to enable automated code coverage analysis.  
This feature would enhance the project by providing clear insights into test coverage, ensuring better code quality and identifying areas that require additional testing.

## Proposed Solution

1. Add the Codecov GitHub Action to the repository's CI workflow file (e.g., `.github/workflows/ci.yml`).  
2. Configure the repository to upload coverage reports to Codecov after running tests.  
3. Include badges in the `README.md` to display the current code coverage status.  
4. Update the `pytest` or equivalent test runner configuration to generate coverage reports in a format supported by Codecov (e.g., `lcov` or `xml`).

Example snippet for GitHub Actions integration:
```yaml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    files: ./coverage.xml  # Adjust path if necessary
    token: ${{ secrets.CODECOV_TOKEN }}
```

## Alternatives Considered

1. Using another code coverage service like Coveralls or SonarCloud.  
2. Manually reviewing and tracking code coverage reports locally.  
However, these alternatives are less integrated and streamlined compared to Codecov.

## Additional Context

Adding Codecov will improve visibility into code coverage metrics directly within pull requests. This integration will help maintain high testing standards and encourage contributors to write comprehensive tests.
